# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 10:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161201_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='words',
            field=models.ManyToManyField(blank=True, to='api.Word'),
        ),
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
