# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20161209_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='group',
        ),
        migrations.AddField(
            model_name='test',
            name='groups',
            field=models.ManyToManyField(blank=True, to='api.Group'),
        ),
    ]
