# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_test_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='userword',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Test'),
            preserve_default=False,
        ),
    ]
