# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 09:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_userword_test'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userword',
            unique_together=set([('user', 'word')]),
        ),
    ]
