# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20161212_0925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['title', 'textbook']},
        ),
        migrations.RemoveField(
            model_name='userword',
            name='last_remider',
        ),
        migrations.AddField(
            model_name='userword',
            name='last_interval',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set([('title', 'textbook')]),
        ),
    ]
