# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170112_0622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userword',
            old_name='following_remider',
            new_name='following_reminder',
        ),
    ]
