# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170112_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='definition_m',
        ),
        migrations.RemoveField(
            model_name='word',
            name='picture_link',
        ),
        migrations.RemoveField(
            model_name='word',
            name='thumbnail_link',
        ),
        migrations.RemoveField(
            model_name='word',
            name='usage_m',
        ),
        migrations.AddField(
            model_name='word',
            name='picture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='sound',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
